services:
  - type: web
    name: resumeiq
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn resume_analyzer.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"